"""Broker protocol. Implementations must not invent trades."""

from __future__ import annotations

from typing import Protocol

from brokers.types import AccountView, BrokerState, OpenOrderView, PositionView, QuoteView, TradeIntent


class Broker(Protocol):
    def get_account(self) -> AccountView | None: ...

    def get_positions(self) -> tuple[PositionView, ...]: ...

    def get_open_orders(self) -> tuple[OpenOrderView, ...]: ...

    def get_quote(self, symbol: str) -> QuoteView | None: ...

    def submit_order(self, order: TradeIntent) -> str: ...

    def cancel_order(self, order_id: str) -> None: ...

    def get_order(self, order_id: str) -> OpenOrderView | None: ...

    def snapshot(self) -> BrokerState: ...
